# Created by: Eugene Kim <astralblue@users.noreply.github.com>

PORTNAME=	ipaddr
DISTVERSION=	1.0.0
CATEGORIES=	net

MAINTAINER=	astralblue@users.noreply.github.com
COMMENT=	Command-line IP address manipulation tool
WWW=		https://github.com/astralblue/ipaddr

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake

USE_GITHUB=	yes
GH_ACCOUNT=	astralblue

PLIST_FILES=	bin/ipaddr \
		share/man/man1/ipaddr.1.gz

.include <bsd.port.mk>
